version: "3.7"

services:
  anon_app:
    container_name: anon_app
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    command: run
    volumes:
      - .:/app/
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    env_file:
      - .env
    ports:
      - 8081:8081
    depends_on:
      - redis
      - postgres_db

  postgres_db:
    image: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${SQL_NAME}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}


  redis:
    container_name: anon_redis
    restart: always
    image: redis:6.0.9-alpine
    expose:
      - 6379

volumes:
  postgres-data: