# Generated by Django 4.1 on 2025-03-18 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название сообщества')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(null=True, verbose_name='описание сообщества')),
                ('is_private', models.BooleanField(default=False)),
                ('application', models.ManyToManyField(related_name='membership_applications', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communities', to=settings.AUTH_USER_MODEL)),
                ('subscribers', models.ManyToManyField(related_name='sub_communities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сообщество',
                'verbose_name_plural': 'Сообщества',
            },
        ),
    ]
